name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libgpg-error-dev
        sudo apt-get install -y autoconf
        sudo apt-get install -y fig2dev
        sudo apt-get install -y texinfo
        sudo apt-get install -y texlive
    - name: autogen
      run: ./autogen.sh
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure --enable-noexecstack --disable-static --enable-m-guard --enable-hmac-binary-check --enable-random=linux --disable-doc
    - name: make
      run: make
    - name: make check
      run: make check
