name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - Install deps:
      run: |
        export APT_DEPENDENCIES=$APT_DEPENDENCIES" libgpg-error"
        sudo apt-get update -qq
        sudo apt-get install -qq
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-noexecstack --disable-static --enable-m-guard --enable-hmac-binary-check --enable-random=linux
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
